// SubFlowElemToElem arguments
realtype *elem_d_ws_gw,
realtype *elem_d_topo_zmin,
// EffKh arguments
realtype *elem_d_soil_areafv,
realtype *elem_d_soil_depth,
realtype *elem_d_soil_dmac,
realtype *elem_d_soil_kmach,
realtype *elem_d_soil_ksath,
// OvlFlowElemToElem
realtype *elem_d_topo_zmax,
realtype *elem_d_lc_rough,
realtype *elem_d_ws_surfh,

int *elem_d_attrib_bc_type0,
int *elem_d_nabr0,
realtype *elem_d_topo_nabrdist0,
realtype *elem_d_topo_edge0,
realtype *elem_d_bc_head0,
realtype *elem_d_bc_flux0,
realtype *elem_d_wf_ovlflow0,
realtype *elem_d_wf_subsurf0,
int *elem_d_attrib_bc_type1,
int *elem_d_nabr1,
realtype *elem_d_topo_nabrdist1,
realtype *elem_d_topo_edge1,
realtype *elem_d_bc_head1,
realtype *elem_d_bc_flux1,
realtype *elem_d_wf_ovlflow1,
realtype *elem_d_wf_subsurf1,
int *elem_d_attrib_bc_type2,
int *elem_d_nabr2,
realtype *elem_d_topo_nabrdist2,
realtype *elem_d_topo_edge2,
realtype *elem_d_bc_head2,
realtype *elem_d_bc_flux2,
realtype *elem_d_wf_ovlflow2,
realtype *elem_d_wf_subsurf2